server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=MyTiptop
    username: sa
    password: '123'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis:
  mapperLocations: classpath:mapper/*.xml   #放在resources下文件夹下时配置
  type-aliases-package: cn.grand.springcloud.entity


#  type-aliases-package: cn.grand.democloud.entities
#  mapper-locations: classpath:mapper/sqlserver/*.xml

eureka:
  client:
    #自己是否注册进EurekaServer 默认 true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true 才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka   #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true  #访问路径可以显示ip地址


